using System.Text;
using System.Collections.Generic;
using System.Linq;
using System;

namespace Basalt.Razor.Vb;

/// <summary>
/// Turns a template into a Blazor component.
/// </summary>
/// <remarks>
/// The same parse tree every other host is written from, emitted differently:
/// a component does not write HTML out as text. It builds a render tree —
/// OpenElement, AddContent, CloseElement — and Blazor diffs one tree against
/// the previous one to decide what to change on screen. A component that wrote
/// markup as text would compile, render nothing, and say nothing about why.
///
/// Every call takes a sequence number, and Blazor's diffing algorithm depends
/// on those numbers being stable between renders rather than on what they
/// count. They are assigned in source order here, which is what the C#
/// compiler does too: numbers derived from a loop counter would change shape
/// between renders and defeat the diff.
///
/// Server, WebAssembly and Auto need nothing different from each other — they
/// differ in where the component runs, not in what is generated for it.
/// </remarks>
public static class VbComponentWriter
{
    /// <summary>
    /// Which tags are open, and whether each is a component.
    /// </summary>
    /// <remarks>
    /// Not a field on a static class in the general case — this writer runs
    /// one template at a time — but kept here so the closing tag knows which
    /// call to make. Reset at the start of every Write.
    /// </remarks>
    [ThreadStatic]
    private static Stack<bool>? _open;

    private static Stack<bool> open_ => _open ??= new Stack<bool>();

    /// <summary>Which open components have child content being written.</summary>
    [ThreadStatic]
    private static Stack<bool>? _fragments;

    private static Stack<bool> fragments_ => _fragments ??= new Stack<bool>();

    /// <summary>
    /// Whether a component opened on this path still needs its child-content
    /// lambda, once its attributes have been written.
    /// </summary>
    [ThreadStatic]
    private static bool pendingFragment_;

    /// <summary>
    /// The builder the calls being written go to.
    /// </summary>
    /// <remarks>
    /// Inside a ChildContent lambda that is the lambda's own parameter, not
    /// the component's: writing to the outer one put the children in the
    /// parent's tree, where the component never looked for them — the box
    /// rendered empty and the content simply disappeared.
    /// </remarks>
    private static string Builder =>
        fragments_.Count > 0 && fragments_.Peek() ? "__child" : "__builder";

    /// <summary>
    /// The namespace a child component is named from.
    /// </summary>
    /// <remarks>
    /// Siblings share a namespace, so a component placed inside another is
    /// found beside it. Set for the run rather than passed down, because the
    /// markup writer is several calls below the one that knows it.
    /// </remarks>
    [ThreadStatic]
    private static string? _componentNamespace;

    private static string ComponentNamespace => _componentNamespace ?? "Basalt.Generated";

    /// <summary>The class every component inherits.</summary>
    public const string ComponentBaseTypeName =
        "Global.Microsoft.AspNetCore.Components.ComponentBase";

    /// <summary>The generated class and where each piece came from.</summary>
    public sealed record Generated(string Code, SourceMap Map)
    {
        public override string ToString() => Code;
    }

    /// <summary>
    /// Writes the component class for a parsed template.
    /// </summary>
    public static string Write(
        VbHtmlDocument document,
        string className,
        string namespaceName,
        string? route = null) =>
        WriteWithMap(document, className, namespaceName, filePath: null, route).Code;

    /// <summary>
    /// Writes the class, recording where each fragment of Visual Basic came
    /// from in the template.
    /// </summary>
    /// <remarks>
    /// The mappings are what the editor runs on: a caret in a component is
    /// moved through them into the generated code, asked about there, and the
    /// answer moved back. Without them a component could be coloured — that
    /// comes from the parser — and could answer nothing else, which reads as
    /// an editor that half works.
    /// </remarks>
    public static Generated WriteWithMap(
        VbHtmlDocument document,
        string className,
        string namespaceName,
        string? filePath,
        string? route = null,
        string? checksum = null,
        bool optionStrict = false)
    {
        var builder = new StringBuilder();
        var mappings = new List<SourceMapping>();
        var sequence = 0;

        open_.Clear();
        fragments_.Clear();
        pendingFragment_ = false;
        _componentNamespace = namespaceName;

        builder.AppendLine("' <auto-generated/>");
        // The project's own setting, as for a view.
        builder.AppendLine(optionStrict ? "Option Strict On" : "Option Strict Off");
        builder.AppendLine("Option Explicit On");
        builder.AppendLine();

        // The web namespace, for the event argument types a handler names.
        builder.AppendLine("Imports Microsoft.AspNetCore.Components.Web");
        builder.AppendLine();

        foreach (var import in document.Imports)
            builder.AppendLine($"Imports {import}");

        if (document.Imports.Count > 0) builder.AppendLine();

        // SHA-256 of the template as read from disk, when the caller has it.
        ExternalSourceWriter.WriteChecksum(builder, filePath, checksum);


        builder.AppendLine($"Namespace {namespaceName}");
        builder.AppendLine();

        // The route the template declared with @Page, unless the caller named
        // one. A component without either is only reachable by being placed
        // inside another, which is not an error.
        route ??= document.PageRoute;

        if (!string.IsNullOrWhiteSpace(route))
            builder.AppendLine($"    <Global.Microsoft.AspNetCore.Components.Route(\"{route}\")>");

        // @Layout "MainLayout": a component's layout is a type, given through
        // Blazor's attribute. It was parsed and then ignored.
        if (!string.IsNullOrWhiteSpace(document.Layout))
        {
            builder.AppendLine(
                $"    <Global.Microsoft.AspNetCore.Components.Layout(GetType({document.Layout}))>");
        }

        var baseType = string.IsNullOrWhiteSpace(document.Inherits)
            ? ComponentBaseTypeName
            : document.Inherits;

        builder.AppendLine($"    Public Class {className}");
        builder.AppendLine($"        Inherits {baseType}");
        builder.AppendLine();

        // Injected services are properties, not constructor arguments: Blazor
        // creates a component with the parameterless constructor and fills
        // these in afterwards.
        foreach (var injected in document.Injected)
        {
            builder.AppendLine("        <Global.Microsoft.AspNetCore.Components.Inject>");
            builder.AppendLine(
                $"        Protected Property {injected.Name} As {injected.Type}");
            builder.AppendLine();
        }

        builder.AppendLine(
            "        Protected Overrides Sub BuildRenderTree(" +
            "__builder As Global.Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder)");

        WriteNodes(builder, document.Nodes, ref sequence, indent: 12, mappings, filePath);

        builder.AppendLine("        End Sub");

        // @functions and @code both land here: methods, fields and properties
        // on the component itself.
        //
        // Mapped line for line, like a view's @Functions, so a breakpoint in
        // an event handler declared here binds to the template.
        foreach (var functions in VbHtmlCodeWriter.FunctionsIn(document.Nodes))
        {
            builder.AppendLine();

            ExternalSourceWriter.WriteMapped(builder, mappings, filePath,
                functions.BodyPosition, functions.Code.Length, functions.BodyLine, () =>
                {
                    foreach (var line in ExternalSourceWriter.LinesOf(functions.Code))
                        builder.AppendLine($"        {line}");
                });
        }

        builder.AppendLine("    End Class");
        builder.AppendLine("End Namespace");

        return new Generated(builder.ToString(), new SourceMap(mappings));
    }

    /// <summary>
    /// Writes a run of nodes, joining the ones that belong together.
    /// </summary>
    /// <remarks>
    /// An attribute whose value is an expression arrives as three nodes — the
    /// markup ending in name=", the expression, the markup starting with " —
    /// because the parser splits on the @ before the tag is ever whole. Writing
    /// them one at a time emitted the tag as text with the expression stranded
    /// in the middle, so onclick="@AddressOf Handler" became an unterminated
    /// string and the component did not compile.
    /// </remarks>
    private static void WriteNodes(
        StringBuilder builder, IReadOnlyList<VbHtmlNode> nodes, ref int sequence, int indent,
        List<SourceMapping> mappings, string? filePath)
    {
        var pad = new string(' ', indent);
        var pending = new List<(string Name, string Value)>();

        // Runs of markup are joined first. The parser ends a node wherever it
        // saw an "@", so "<input @bind=" arrives as two markup nodes and the
        // tag cannot be read as a whole — the element was never opened and the
        // marker was written into the page as text.
        nodes = JoinMarkup(nodes);

        for (var i = 0; i < nodes.Count; i++)
        {
            if (nodes[i] is HtmlNode html
                && i + 2 < nodes.Count
                && nodes[i + 1] is ExpressionNode expression
                && nodes[i + 2] is HtmlNode after
                && AttributeNameAt(html.Text) is { } name)
            {
                // The markup before the attribute ends inside the tag it
                // belongs to — "<button " — so it cannot be written as literal
                // markup: Blazor refuses an attribute that does not follow an
                // element frame, and the page failed at render with
                // "Attributes may only be added immediately after frames of
                // type Element or Component". The element is opened properly
                // and only what precedes the tag is written as markup.
                var before = html.Text.Substring(
                    0, html.Text.Length - name.Length - 2);

                var tagAt = before.LastIndexOf('<');

                if (tagAt >= 0 && before.IndexOf('>', tagAt) < 0)
                {
                    WriteMarkup(builder, before.Substring(0, tagAt), ref sequence, pad, pending);

                    var element = Name(before.Substring(tagAt + 1).TrimStart());

                    // A capitalised tag is a component here too. Opening it as
                    // an element sent an invented tag to the browser and lost
                    // every parameter, the same way it did on the plain path.
                    if (IsComponentName(element))
                    {
                        builder.AppendLine(
                            $"{pad}{Builder}.OpenComponent(Of {ComponentType(element)})({sequence++})");

                        open_.Push(true);

                        // Opened for child content once the tag's attributes
                        // are written, further down: a component reached
                        // through this path — because one of its attributes is
                        // an expression — was opened and its children were
                        // emitted as the parent's frames, so nothing inside it
                        // rendered at all.
                        pendingFragment_ = true;
                    }
                    else
                    {
                        builder.AppendLine(
                            $"{pad}{Builder}.OpenElement({sequence++}, \"{element}\")");

                        open_.Push(false);
                    }

                    // Any attributes already written inside the tag before this
                    // one, which would otherwise be lost with the literal.
                    var written = before.Substring(tagAt + 1 + element.Length);

                    WriteAttributes(builder, written, ref sequence, pad);
                }
                else
                {
                    WriteMarkup(builder, before, ref sequence, pad, pending);
                }

                // A binding is two attributes here as well: this is the path
                // an attribute takes when its value is an expression, which is
                // exactly what @bind="@x" is.
                if (IsBind(name))
                    WriteBinding(builder, name, expression.Expression, ref sequence, pad);
                else
                    builder.AppendLine(
                        $"{pad}{Builder}.AddAttribute({sequence++}, \"{name}\", " +
                        $"{Expression(expression.Expression)})");

                var rest = after.Text.Substring(1);

                // Only when the tag has content. A self-closing component
                // opened a child-content lambda that nothing ever closed, so
                // the generated file ended mid-statement — "End Sub expected",
                // pointing at generated code rather than at the template.
                var selfCloses = rest.TrimStart().StartsWith("/>", StringComparison.Ordinal);

                if (pendingFragment_ && !selfCloses)
                {
                    pendingFragment_ = false;

                    builder.AppendLine(
                        $"{pad}{Builder}.AddAttribute({sequence++}, \"ChildContent\", " +
                        "CType(Sub(__child As Global.Microsoft.AspNetCore.Components." +
                        "Rendering.RenderTreeBuilder)");

                    fragments_.Push(true);
                }
                else
                {
                    pendingFragment_ = false;
                }

                // The closing literal starts with the quote that ended the
                // attribute value, and — when the tag ends there — with the
                // ">" closing the tag as well. Both belong to markup already
                // turned into calls: leaving them in put a stray ">" in the
                // page, and Blazor writes the tag's own bracket.
                var skipped = 1;

                // What closes the tag belongs to the calls already written, not
                // to the page: a self-closing tag left " />" behind as text and
                // never closed the element or component it opened.
                var closes = rest.TrimStart();

                if (closes.StartsWith("/>", StringComparison.Ordinal))
                {
                    var wasComponent = open_.Count > 0 && open_.Pop();

                    builder.AppendLine(wasComponent
                        ? $"{pad}{Builder}.CloseComponent()"
                        : $"{pad}{Builder}.CloseElement()");

                    skipped += rest.Length - closes.Length + 2;
                    rest = closes.Substring(2);
                }
                else if (closes.StartsWith(">", StringComparison.Ordinal))
                {
                    skipped += rest.Length - closes.Length + 1;
                    rest = closes.Substring(1);
                }

                nodes = Replace(nodes, i + 2, new HtmlNode(
                    rest, after.Position + skipped, after.Line));

                i++;
                continue;
            }

            WriteNode(builder, nodes[i], ref sequence, indent, mappings, filePath);
        }
    }

    /// <summary>
    /// Markup nodes that sit next to each other, as one node.
    /// </summary>
    private static IReadOnlyList<VbHtmlNode> JoinMarkup(IReadOnlyList<VbHtmlNode> nodes)
    {
        var joined = new List<VbHtmlNode>(nodes.Count);

        foreach (var node in nodes)
        {
            if (node is HtmlNode html
                && joined.Count > 0
                && joined[joined.Count - 1] is HtmlNode previous)
            {
                joined[joined.Count - 1] = new HtmlNode(
                    previous.Text + html.Text, previous.Position, previous.Line);

                continue;
            }

            joined.Add(node);
        }

        return joined;
    }

    /// <summary>The attribute name a run of markup ends by opening.</summary>
    private static string? AttributeNameAt(string markup)
    {
        if (!markup.EndsWith("=\"", StringComparison.Ordinal)) return null;

        var end = markup.Length - 2;
        var start = end;

        while (start > 0 && !char.IsWhiteSpace(markup[start - 1])) start--;

        return end > start ? markup.Substring(start, end - start) : null;
    }

    private static IReadOnlyList<VbHtmlNode> Replace(
        IReadOnlyList<VbHtmlNode> nodes, int at, VbHtmlNode with)
    {
        var copy = nodes.ToList();
        copy[at] = with;

        return copy;
    }

    private static void WriteNode(
        StringBuilder builder, VbHtmlNode node, ref int sequence, int indent,
        List<SourceMapping> mappings, string? filePath)
    {
        var pad = new string(' ', indent);

        switch (node)
        {
            case HtmlNode html:
                WriteMarkup(builder, html.Text, ref sequence, pad, null);
                break;

            case ExpressionNode expression:
                // AddContent encodes what it is given, which is what an
                // implicit expression means. Raw output goes through
                // MarkupString, the way it does in C#.
                var value = expression.IsAwaited
                    ? $"Await {expression.Expression}"
                    : expression.Expression;

                // Raw output goes through MarkupString, the way @Html.Raw does
                // in a view: AddContent encodes anything else, which is what an
                // implicit expression means.
                var wrapper = expression.IsRaw
                    ? "New Global.Microsoft.AspNetCore.Components.MarkupString(Global.System.Convert.ToString("
                    : "";

                if (expression.IsRaw) value = $"{wrapper}{value}))";

                var seq = sequence++;

                // Through a local on a line of its own, so the mapped region
                // begins where the expression begins. #ExternalSource has to
                // start its own line, so the expression cannot be mapped
                // inside the AddContent call — and mapping the whole line
                // instead put the caret before "__builder", far enough out
                // that Roslyn was asked about the wrong token.
                //
                // The view writer maps whole lines and gets away with it only
                // because "Write(" is short enough that the drift still lands
                // inside the expression.
                var local = $"__v{seq}";

                // The mapping starts at the template's own text in the line,
                // past "Dim __v0 = " and any MarkupString around it; counted,
                // not searched for, since a one-letter name is also in "Dim".
                var before = $"{pad}Dim {local} = {wrapper}";
                var line = $"{pad}Dim {local} = {value}";

                VbHtmlCodeWriter.WriteExpressionMapped(builder, mappings, filePath, expression, before, line);

                builder.AppendLine($"{pad}{Builder}.AddContent({seq}, {local})");
                break;

            case StatementNode statement:
                // From the body, line for line, as a view does: the whole block
                // written as one line put its second line at the left margin
                // and anchored the pragma at "@Code" rather than at the first
                // statement, a line early.
                WriteMapped(builder, mappings, filePath,
                    statement.BodyPosition, statement.Code.Length, statement.BodyLine,
                    () =>
                    {
                        foreach (var line in ExternalSourceWriter.LinesOf(statement.Code))
                            builder.AppendLine($"{pad}{line}");
                    });
                break;

            case BlockNode block:
                // The opening clause carries the interesting expression — the
                // condition of an If, the source of a For Each — so a caret
                // there must reach Roslyn. Mapping only the body left every
                // question asked inside a condition unanswered.
                WriteMapped(builder, mappings, filePath,
                    block.Position + 1, block.Opening.Length, block.Line,
                    () => builder.AppendLine($"{pad}{block.Opening}"));

                foreach (var child in VbHtmlCodeWriter.BodyOf(block))
                    WriteNode(builder, child, ref sequence, indent + 4, mappings, filePath);

                foreach (var clause in block.Clauses)
                {
                    VbHtmlCodeWriter.WriteClosingOrClause(builder, mappings, filePath, pad,
                        clause.Keyword, clause.Position, clause.Line);

                    foreach (var child in clause.Body)
                        WriteNode(builder, child, ref sequence, indent + 4, mappings, filePath);
                }

                VbHtmlCodeWriter.WriteClosingOrClause(builder, mappings, filePath, pad,
                    block.Closing, block.ClosingPosition, block.ClosingLine);
                break;

            case FunctionsNode:
            case DirectiveNode:
                // Written outside BuildRenderTree, or consumed by the header.
                break;

            case SectionNode:
                // Sections belong to a layout, which a component does not
                // have: its equivalent is a RenderFragment parameter, and
                // silently emitting nothing is better than emitting a section
                // the runtime will never look for.
                break;
        }
    }

    /// <summary>
    /// Writes one fragment, recording where it came from. See
    /// <see cref="ExternalSourceWriter"/>, which views share.
    /// </summary>
    private static void WriteMapped(
        StringBuilder builder,
        List<SourceMapping> mappings,
        string? filePath,
        int originalPosition,
        int originalLength,
        int originalLine,
        Action write,
        int offset = 0) =>
        ExternalSourceWriter.WriteMapped(
            builder, mappings, filePath, originalPosition, originalLength, originalLine, write, offset);


    /// <summary>
    /// Writes a run of markup as element calls.
    /// </summary>
    /// <remarks>
    /// Element by element rather than as one blob of markup: Blazor can only
    /// diff what it can see the shape of, and a whole page handed over as text
    /// is replaced wholesale on every change rather than patched.
    /// </remarks>
    private static void WriteMarkup(
        StringBuilder builder, string markup, ref int sequence, string pad,
        List<(string Name, string Value)>? pending)
    {
        var at = 0;

        while (at < markup.Length)
        {
            var open = markup.IndexOf('<', at);

            if (open < 0)
            {
                AddText(builder, markup.Substring(at), ref sequence, pad);
                break;
            }

            if (open > at) AddText(builder, markup.Substring(at, open - at), ref sequence, pad);

            var close = markup.IndexOf('>', open);

            if (close < 0)
            {
                // An unterminated tag is text, not a broken element: a
                // template being typed into is unparseable most of the time.
                AddText(builder, markup.Substring(open), ref sequence, pad);
                break;
            }

            var tag = markup.Substring(open + 1, close - open - 1).Trim();

            if (tag.StartsWith("/", StringComparison.Ordinal))
            {
                // Which kind of thing is being closed has to be remembered:
                // a component is closed with CloseComponent and an element
                // with CloseElement, and calling the wrong one leaves the
                // render tree unbalanced for the rest of the component.
                var wasComponent = open_.Count > 0 && open_.Pop();

                if (wasComponent && fragments_.Count > 0 && fragments_.Pop())
                {
                    // The lambda opened for ChildContent, then the component.
                    builder.AppendLine(
                        $"{pad}End Sub, Global.Microsoft.AspNetCore.Components.RenderFragment))");
                }

                builder.AppendLine(wasComponent
                    ? $"{pad}{Builder}.CloseComponent()"
                    : $"{pad}{Builder}.CloseElement()");
            }
            else
            {
                var selfClosing = tag.EndsWith("/", StringComparison.Ordinal);
                var name = Name(tag);
                var attributes = tag.Substring(name.Length).TrimEnd('/').Trim();

                // A capitalised tag is another component, the way it is in
                // Razor: <Saluto Nome="x" /> was written out as an element
                // called "Saluto", so the browser received an invented tag
                // and the parameter was dropped on the floor.
                if (IsComponentName(name))
                {
                    // Unqualified, so Visual Basic resolves it the way it
                    // resolves any name in the file's own namespace. Rooting
                    // it at Global and naming the namespace we wrote produced
                    // Global.Components.Saluto, which misses the RootNamespace
                    // the compiler prepends — the class is really
                    // App.Components.Saluto, and the generator cannot know
                    // what App is because it deliberately does not write it.
                    builder.AppendLine(
                        $"{pad}{Builder}.OpenComponent(Of {ComponentType(name)})({sequence++})");

                    WriteComponentParameters(builder, attributes, ref sequence, pad);

                    if (selfClosing)
                    {
                        builder.AppendLine($"{pad}{Builder}.CloseComponent()");
                    }
                    else
                    {
                        // What sits between the tags becomes ChildContent, a
                        // RenderFragment the component decides where to put.
                        // Written straight into the tree instead, it was
                        // emitted as the component's own frames and vanished:
                        // the box rendered and everything inside it was gone.
                        builder.AppendLine(
                            $"{pad}{Builder}.AddAttribute({sequence++}, \"ChildContent\", " +
                            "CType(Sub(__child As Global.Microsoft.AspNetCore.Components." +
                            "Rendering.RenderTreeBuilder)");

                        open_.Push(true);
                        fragments_.Push(true);
                    }
                }
                else
                {
                    builder.AppendLine($"{pad}{Builder}.OpenElement({sequence++}, \"{name}\")");

                    WriteAttributes(builder, attributes, ref sequence, pad);

                    if (selfClosing || IsVoid(name))
                        builder.AppendLine($"{pad}{Builder}.CloseElement()");
                    else
                        open_.Push(false);
                }
            }

            at = close + 1;
        }
    }

    private static void AddText(
        StringBuilder builder, string text, ref int sequence, string pad)
    {
        if (text.Length == 0) return;

        // AddMarkupContent, not AddContent: literal markup from the template
        // is already markup, and AddContent encodes it — the line breaks
        // between elements came out as &#xA; in the page.
        builder.AppendLine($"{pad}{Builder}.AddMarkupContent({sequence++}, {Quoted(text)})");
    }

    private static void WriteAttributes(
        StringBuilder builder, string attributes, ref int sequence, string pad)
    {
        foreach (var (name, value) in Attributes(attributes))
        {
            // @bind is two attributes, not one: the value going out and the
            // handler bringing the change back. Written as a single attribute
            // called "bind" the browser received a meaningless one and nothing
            // was ever read back — a form that looked right and lost every
            // keystroke.
            if (IsBind(name))
            {
                WriteBinding(builder, name, value, ref sequence, pad);
                continue;
            }

            // An @ in the value is Visual Basic, not text: onclick="@Handler"
            // has to reach AddAttribute as an expression or the handler is
            // registered as the literal string.
            var written = value.StartsWith("@", StringComparison.Ordinal)
                ? Expression(value.Substring(1))
                : Quoted(value);

            builder.AppendLine($"{pad}{Builder}.AddAttribute({sequence++}, \"{name}\", {written})");
        }
    }

    /// <summary>Whether an attribute asks for two-way binding.</summary>
    /// <remarks>
    /// Both spellings: Razor writes @bind on an element and @bind-Value on a
    /// component's parameter, and the second is the one every input component
    /// in the framework expects.
    /// </remarks>
    private static bool IsBind(string name)
    {
        // With or without the marker: the parser keeps "@" as a node of its
        // own, so by the time an attribute name is read here the "@" may
        // already have been consumed as separate markup.
        var bare = name.StartsWith("@", StringComparison.Ordinal)
            ? name.Substring(1)
            : name;

        return bare.Equals("bind", StringComparison.OrdinalIgnoreCase)
            || bare.StartsWith("bind-", StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Writes a two-way binding as the pair of attributes it really is.
    /// </summary>
    /// <remarks>
    /// The value is formatted by BindConverter, which knows how each type is
    /// written into an attribute — a date is not written the way a number is,
    /// and doing it with ToString gives a value the browser sends back
    /// unparseable.
    ///
    /// The handler comes from CreateBinder, which parses what arrives back
    /// into the target's type and assigns it. Written by hand it would be a
    /// parse per type here, disagreeing with the framework's own as soon as
    /// either changed.
    /// </remarks>
    private static void WriteBinding(
        StringBuilder builder, string name, string value, ref int sequence, string pad)
    {
        var target = value.StartsWith("@", StringComparison.Ordinal)
            ? value.Substring(1).Trim()
            : value.Trim();

        // @bind-Value on a component sets Value and ValueChanged; a plain
        // @bind on an element sets value and listens for onchange.
        var bare = name.StartsWith("@", StringComparison.Ordinal)
            ? name.Substring(1)
            : name;

        var component = bare.StartsWith("bind-", StringComparison.OrdinalIgnoreCase);

        var attribute = component ? bare.Substring("bind-".Length) : "value";
        var changed = component ? attribute + "Changed" : "onchange";

        builder.AppendLine(
            $"{pad}{Builder}.AddAttribute({sequence++}, \"{attribute}\", " +
            $"Global.Microsoft.AspNetCore.Components.BindConverter.FormatValue({target}))");

        builder.AppendLine(
            $"{pad}{Builder}.AddAttribute({sequence++}, \"{changed}\", " +
            // Called as the shared method it really is. CreateBinder is an
            // extension, and Visual Basic does not apply extensions to a
            // fully qualified chain: written as
            // Global.….EventCallback.Factory.CreateBinder(…) it failed to
            // resolve even with the namespace imported — measured in a
            // hand-written file, so it is the language rather than the
            // generator.
            "Global.Microsoft.AspNetCore.Components." +
            "EventCallbackFactoryBinderExtensions.CreateBinder(" +
            "Global.Microsoft.AspNetCore.Components.EventCallback.Factory, " +
            $"Me, Sub(__value) {target} = __value, {target}))");
    }

    /// <summary>
    /// An attribute value that is Visual Basic rather than text.
    /// </summary>
    /// <remarks>
    /// A method reference is wrapped in an EventCallback. AddAttribute has no
    /// overload taking a bare delegate, so onclick="@AddressOf Go" compiled to
    /// a call that did not resolve — "no accessible AddAttribute can be called
    /// with these arguments", pointing at generated code rather than at the
    /// template. The C# compiler does the same wrapping for @onclick.
    /// </remarks>
    private static string Expression(string code)
    {
        var trimmed = code.Trim();

        return trimmed.StartsWith("AddressOf", StringComparison.Ordinal)
            ? "Global.Microsoft.AspNetCore.Components.EventCallback.Factory.Create(Me, " +
              trimmed + ")"
            : trimmed;
    }

    /// <summary>The attributes in a tag, as name and value.</summary>
    private static IEnumerable<(string Name, string Value)> Attributes(string text)
    {
        var at = 0;

        while (at < text.Length)
        {
            while (at < text.Length && char.IsWhiteSpace(text[at])) at++;

            if (at >= text.Length) break;

            var equals = text.IndexOf('=', at);

            if (equals < 0)
            {
                // A bare attribute is true, the way "disabled" is in HTML.
                var bare = text.Substring(at).Trim();

                if (bare.Length > 0) yield return (bare, "@True");

                break;
            }

            var name = text.Substring(at, equals - at).Trim();
            var from = equals + 1;

            while (from < text.Length && char.IsWhiteSpace(text[from])) from++;

            if (from >= text.Length) break;

            var quote = text[from];

            if (quote is '"' or '\'')
            {
                var end = text.IndexOf(quote, from + 1);

                if (end < 0) break;

                yield return (name, text.Substring(from + 1, end - from - 1));
                at = end + 1;
            }
            else
            {
                var end = from;

                while (end < text.Length && !char.IsWhiteSpace(text[end])) end++;

                yield return (name, text.Substring(from, end - from));
                at = end;
            }
        }
    }

    /// <summary>
    /// Whether a tag names another component rather than an HTML element.
    /// </summary>
    /// <remarks>
    /// By its first letter, which is how Razor decides too: HTML element names
    /// are lower case by convention and a component is a class, so the case is
    /// the whole distinction. A lower-case component name is unreachable this
    /// way, which is the same limitation C# has.
    /// </remarks>
    private static bool IsComponentName(string name) =>
        name.Length > 0 && char.IsUpper(name[0]);

    /// <summary>
    /// The type a component tag names, ready to be written.
    /// </summary>
    /// <remarks>
    /// A sibling is named unqualified so Visual Basic finds it in the file's
    /// own namespace, and the compiler's RootNamespace is applied for us. The
    /// framework's own components are not siblings and have to be named in
    /// full, or CascadingValue resolves to nothing at all.
    ///
    /// CascadingValue is generic over what it carries, and the type has to
    /// match what the receiving side asks for: Of Object made the cascade
    /// carry an Object, which matched no parameter at all — the child rendered
    /// with its property left empty and nothing said why. Visual Basic will
    /// not infer it either, so String is written, which is what a cascade
    /// carries in practice. A cascade of another type needs the component
    /// written by hand for now.
    /// </remarks>
    private static string ComponentType(string name)
    {
        // A type argument written into the tag: <Elenco(Of String) … />. The
        // C# compiler infers this from the parameter values, which needs the
        // type system; here the template says it. Without a way to say it a
        // generic component could not be used at all — the call failed with
        // "too few type arguments", against generated code.
        var generic = name.IndexOf("(Of ", StringComparison.OrdinalIgnoreCase);

        if (generic > 0) return name;

        return Known(name);
    }

    private static string Known(string name) => name switch
    {
        "CascadingValue" =>
            "Global.Microsoft.AspNetCore.Components.CascadingValue(Of String)",
        "DynamicComponent" =>
            "Global.Microsoft.AspNetCore.Components.DynamicComponent",
        _ => name
    };

    /// <summary>
    /// The parameters passed to a child component.
    /// </summary>
    /// <remarks>
    /// AddComponentParameter rather than AddAttribute: a parameter is set on
    /// the component object, not written into the markup, and the two are
    /// different frames in the render tree.
    /// </remarks>
    private static void WriteComponentParameters(
        StringBuilder builder, string attributes, ref int sequence, string pad)
    {
        foreach (var (name, value) in Attributes(attributes))
        {
            var written = value.StartsWith("@", StringComparison.Ordinal)
                ? Expression(value.Substring(1))
                : Quoted(value);

            builder.AppendLine(
                $"{pad}{Builder}.AddComponentParameter({sequence++}, \"{name}\", {written})");
        }
    }

    /// <summary>The element name at the start of a tag.</summary>
    private static string Name(string tag)
    {
        // A type argument belongs to the name: <Elenco(Of String) …> read a
        // character at a time stops at the bracket and leaves "(Of String)" to
        // be taken for attributes, so the whole thing is claimed first.
        var generic = tag.IndexOf("(Of ", StringComparison.OrdinalIgnoreCase);

        if (generic > 0)
        {
            var close = tag.IndexOf(')', generic);

            if (close > 0 && tag.Substring(0, generic).IndexOf(' ') < 0)
                return tag.Substring(0, close + 1);
        }

        var end = 0;

        while (end < tag.Length && !char.IsWhiteSpace(tag[end]) && tag[end] != '/') end++;

        return tag.Substring(0, end);
    }

    /// <summary>
    /// Whether an element closes itself in HTML.
    /// </summary>
    /// <remarks>
    /// A void element has no closing tag to find, so without this the builder
    /// is left with an element open and everything after it nests inside a
    /// &lt;br&gt; — the tree stays unbalanced to the end of the component.
    /// </remarks>
    private static bool IsVoid(string name) => name.ToLowerInvariant() is
        "area" or "base" or "br" or "col" or "embed" or "hr" or "img" or
        "input" or "link" or "meta" or "source" or "track" or "wbr";

    /// <summary>
    /// A Visual Basic string literal.
    /// </summary>
    /// <remarks>
    /// Line breaks become vbLf rather than being written into the literal:
    /// Visual Basic has no multi-line string, so markup spanning lines — which
    /// is all markup — produced a literal broken across lines and a file that
    /// did not compile.
    /// </remarks>
    private static string Quoted(string text)
    {
        var parts = text.Replace("\r\n", "\n").Split('\n');
        var pieces = new List<string>();

        for (var i = 0; i < parts.Length; i++)
        {
            if (i > 0) pieces.Add("Global.Microsoft.VisualBasic.Constants.vbLf");

            if (parts[i].Length > 0)
                pieces.Add("\"" + parts[i].Replace("\"", "\"\"") + "\"");
        }

        return pieces.Count == 0 ? "\"\"" : string.Join(" & ", pieces);
    }
}
