using System.Text;
using System.Collections.Generic;
using System.Linq;
using System;

namespace Basalt.Razor.Vb;

/// <summary>
/// Turns a template into a Blazor component.
/// </summary>
/// <remarks>
/// The same parse tree every other host is written from, emitted differently:
/// a component does not write HTML out as text. It builds a render tree —
/// OpenElement, AddContent, CloseElement — and Blazor diffs one tree against
/// the previous one to decide what to change on screen. A component that wrote
/// markup as text would compile, render nothing, and say nothing about why.
///
/// Every call takes a sequence number, and Blazor's diffing algorithm depends
/// on those numbers being stable between renders rather than on what they
/// count. They are assigned in source order here, which is what the C#
/// compiler does too: numbers derived from a loop counter would change shape
/// between renders and defeat the diff.
///
/// Server, WebAssembly and Auto need nothing different from each other — they
/// differ in where the component runs, not in what is generated for it.
/// </remarks>
public static class VbComponentWriter
{
    /// <summary>The class every component inherits.</summary>
    public const string ComponentBaseTypeName =
        "Global.Microsoft.AspNetCore.Components.ComponentBase";

    /// <summary>The generated class and where each piece came from.</summary>
    public sealed record Generated(string Code, SourceMap Map)
    {
        public override string ToString() => Code;
    }

    /// <summary>
    /// Writes the component class for a parsed template.
    /// </summary>
    public static string Write(
        VbHtmlDocument document,
        string className,
        string namespaceName,
        string? route = null) =>
        WriteWithMap(document, className, namespaceName, filePath: null, route).Code;

    /// <summary>
    /// Writes the class, recording where each fragment of Visual Basic came
    /// from in the template.
    /// </summary>
    /// <remarks>
    /// The mappings are what the editor runs on: a caret in a component is
    /// moved through them into the generated code, asked about there, and the
    /// answer moved back. Without them a component could be coloured — that
    /// comes from the parser — and could answer nothing else, which reads as
    /// an editor that half works.
    /// </remarks>
    public static Generated WriteWithMap(
        VbHtmlDocument document,
        string className,
        string namespaceName,
        string? filePath,
        string? route = null)
    {
        var builder = new StringBuilder();
        var mappings = new List<SourceMapping>();
        var sequence = 0;

        builder.AppendLine("' <auto-generated/>");
        builder.AppendLine("Option Strict Off");
        builder.AppendLine("Option Explicit On");
        builder.AppendLine();

        foreach (var import in document.Imports)
            builder.AppendLine($"Imports {import}");

        if (document.Imports.Count > 0) builder.AppendLine();

        builder.AppendLine($"Namespace {namespaceName}");
        builder.AppendLine();

        // The route the template declared with @Page, unless the caller named
        // one. A component without either is only reachable by being placed
        // inside another, which is not an error.
        route ??= document.PageRoute;

        if (!string.IsNullOrWhiteSpace(route))
            builder.AppendLine($"    <Global.Microsoft.AspNetCore.Components.Route(\"{route}\")>");

        var baseType = string.IsNullOrWhiteSpace(document.Inherits)
            ? ComponentBaseTypeName
            : document.Inherits;

        builder.AppendLine($"    Public Class {className}");
        builder.AppendLine($"        Inherits {baseType}");
        builder.AppendLine();

        // Injected services are properties, not constructor arguments: Blazor
        // creates a component with the parameterless constructor and fills
        // these in afterwards.
        foreach (var injected in document.Injected)
        {
            builder.AppendLine("        <Global.Microsoft.AspNetCore.Components.Inject>");
            builder.AppendLine(
                $"        Protected Property {injected.Name} As {injected.Type}");
            builder.AppendLine();
        }

        builder.AppendLine(
            "        Protected Overrides Sub BuildRenderTree(" +
            "__builder As Global.Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder)");

        WriteNodes(builder, document.Nodes, ref sequence, indent: 12, mappings, filePath);

        builder.AppendLine("        End Sub");

        // @functions and @code both land here: methods, fields and properties
        // on the component itself.
        foreach (var functions in document.Nodes.OfType<FunctionsNode>())
        {
            builder.AppendLine();
            builder.AppendLine(functions.Code);
        }

        builder.AppendLine("    End Class");
        builder.AppendLine("End Namespace");

        return new Generated(builder.ToString(), new SourceMap(mappings));
    }

    /// <summary>
    /// Writes a run of nodes, joining the ones that belong together.
    /// </summary>
    /// <remarks>
    /// An attribute whose value is an expression arrives as three nodes — the
    /// markup ending in name=", the expression, the markup starting with " —
    /// because the parser splits on the @ before the tag is ever whole. Writing
    /// them one at a time emitted the tag as text with the expression stranded
    /// in the middle, so onclick="@AddressOf Handler" became an unterminated
    /// string and the component did not compile.
    /// </remarks>
    private static void WriteNodes(
        StringBuilder builder, IReadOnlyList<VbHtmlNode> nodes, ref int sequence, int indent,
        List<SourceMapping> mappings, string? filePath)
    {
        var pad = new string(' ', indent);
        var pending = new List<(string Name, string Value)>();

        for (var i = 0; i < nodes.Count; i++)
        {
            if (nodes[i] is HtmlNode html
                && i + 2 < nodes.Count
                && nodes[i + 1] is ExpressionNode expression
                && nodes[i + 2] is HtmlNode after
                && AttributeNameAt(html.Text) is { } name)
            {
                // The markup before the attribute still has to be written; the
                // attribute itself becomes an AddAttribute call once the
                // element is open.
                var before = html.Text.Substring(
                    0, html.Text.Length - name.Length - 2);

                WriteMarkup(builder, before, ref sequence, pad, pending);

                builder.AppendLine(
                    $"{pad}__builder.AddAttribute({sequence++}, \"{name}\", {expression.Expression})");

                // The closing literal opens whatever follows, so only its
                // leading quote is consumed here.
                nodes = Replace(nodes, i + 2, new HtmlNode(
                    after.Text.Substring(1), after.Position + 1, after.Line));

                i++;
                continue;
            }

            WriteNode(builder, nodes[i], ref sequence, indent, mappings, filePath);
        }
    }

    /// <summary>The attribute name a run of markup ends by opening.</summary>
    private static string? AttributeNameAt(string markup)
    {
        if (!markup.EndsWith("=\"", StringComparison.Ordinal)) return null;

        var end = markup.Length - 2;
        var start = end;

        while (start > 0 && !char.IsWhiteSpace(markup[start - 1])) start--;

        return end > start ? markup.Substring(start, end - start) : null;
    }

    private static IReadOnlyList<VbHtmlNode> Replace(
        IReadOnlyList<VbHtmlNode> nodes, int at, VbHtmlNode with)
    {
        var copy = nodes.ToList();
        copy[at] = with;

        return copy;
    }

    private static void WriteNode(
        StringBuilder builder, VbHtmlNode node, ref int sequence, int indent,
        List<SourceMapping> mappings, string? filePath)
    {
        var pad = new string(' ', indent);

        switch (node)
        {
            case HtmlNode html:
                WriteMarkup(builder, html.Text, ref sequence, pad, null);
                break;

            case ExpressionNode expression:
                // AddContent encodes what it is given, which is what an
                // implicit expression means. Raw output goes through
                // MarkupString, the way it does in C#.
                var value = expression.IsAwaited
                    ? $"Await {expression.Expression}"
                    : expression.Expression;

                // Raw output goes through MarkupString, the way @Html.Raw does
                // in a view: AddContent encodes anything else, which is what an
                // implicit expression means.
                if (expression.IsRaw)
                    value = $"New Global.Microsoft.AspNetCore.Components.MarkupString(" +
                            $"Global.System.Convert.ToString({value}))";

                var seq = sequence++;

                // Through a local on a line of its own, so the mapped region
                // begins where the expression begins. #ExternalSource has to
                // start its own line, so the expression cannot be mapped
                // inside the AddContent call — and mapping the whole line
                // instead put the caret before "__builder", far enough out
                // that Roslyn was asked about the wrong token.
                //
                // The view writer maps whole lines and gets away with it only
                // because "Write(" is short enough that the drift still lands
                // inside the expression.
                var local = $"__v{seq}";

                WriteMapped(builder, mappings, filePath,
                    expression.Position + 1, expression.Expression.Length, expression.Line,
                    () => builder.AppendLine($"{pad}Dim {local} = {value}"),
                    offset: $"{pad}Dim {local} = ".Length);

                builder.AppendLine($"{pad}__builder.AddContent({seq}, {local})");
                break;

            case StatementNode statement:
                WriteMapped(builder, mappings, filePath,
                    statement.BodyPosition, statement.Code.Length, statement.Line,
                    () => builder.AppendLine($"{pad}{statement.Code}"));
                break;

            case BlockNode block:
                // The opening clause carries the interesting expression — the
                // condition of an If, the source of a For Each — so a caret
                // there must reach Roslyn. Mapping only the body left every
                // question asked inside a condition unanswered.
                WriteMapped(builder, mappings, filePath,
                    block.Position + 1, block.Opening.Length, block.Line,
                    () => builder.AppendLine($"{pad}{block.Opening}"));

                foreach (var child in block.Body)
                    WriteNode(builder, child, ref sequence, indent + 4, mappings, filePath);

                foreach (var clause in block.Clauses)
                {
                    builder.AppendLine($"{pad}{clause.Keyword}");

                    foreach (var child in clause.Body)
                        WriteNode(builder, child, ref sequence, indent + 4, mappings, filePath);
                }

                builder.AppendLine($"{pad}{block.Closing}");
                break;

            case FunctionsNode:
            case DirectiveNode:
                // Written outside BuildRenderTree, or consumed by the header.
                break;

            case SectionNode:
                // Sections belong to a layout, which a component does not
                // have: its equivalent is a RenderFragment parameter, and
                // silently emitting nothing is better than emitting a section
                // the runtime will never look for.
                break;
        }
    }

    /// <summary>
    /// Writes one fragment, recording where it came from.
    /// </summary>
    /// <remarks>
    /// The same shape the view writer uses, and for the same reason:
    /// #ExternalSource makes the Visual Basic compiler blame the template
    /// rather than generated code nobody wrote, and the mapping lets the
    /// editor move a caret between the two.
    /// </remarks>
    private static void WriteMapped(
        StringBuilder builder,
        List<SourceMapping> mappings,
        string? filePath,
        int originalPosition,
        int originalLength,
        int originalLine,
        Action write,
        int offset = 0)
    {
        if (filePath is null)
        {
            write();
            return;
        }

        builder.AppendLine($"#ExternalSource(\"{filePath.Replace("\\", "\\\\")}\", {originalLine + 1})");

        var start = builder.Length;
        var generatedLine = CountLines(builder, start);

        write();

        var length = builder.Length - start;

        // A directive has to start its own line, and a fragment written with
        // Append rather than AppendLine leaves the builder mid-line: without
        // this the directive was glued to the end of the expression and the
        // generated file did not compile.
        if (builder.Length > 0 && builder[builder.Length - 1] != '\n')
            builder.AppendLine();

        builder.AppendLine("#End ExternalSource");

        // The offset skips whatever the line puts in front of the expression,
        // so a caret in the template lands on the matching character rather
        // than at the start of the statement carrying it.
        mappings.Add(new SourceMapping(
            new SourceSpan(originalPosition, originalLength),
            new SourceSpan(start + offset, Math.Max(0, length - offset)),
            originalLine,
            generatedLine));
    }

    /// <summary>How many lines precede an offset.</summary>
    private static int CountLines(StringBuilder builder, int offset)
    {
        var lines = 0;

        for (var i = 0; i < offset && i < builder.Length; i++)
            if (builder[i] == '\n') lines++;

        return lines;
    }

    /// <summary>
    /// Writes a run of markup as element calls.
    /// </summary>
    /// <remarks>
    /// Element by element rather than as one blob of markup: Blazor can only
    /// diff what it can see the shape of, and a whole page handed over as text
    /// is replaced wholesale on every change rather than patched.
    /// </remarks>
    private static void WriteMarkup(
        StringBuilder builder, string markup, ref int sequence, string pad,
        List<(string Name, string Value)>? pending)
    {
        var at = 0;

        while (at < markup.Length)
        {
            var open = markup.IndexOf('<', at);

            if (open < 0)
            {
                AddText(builder, markup.Substring(at), ref sequence, pad);
                break;
            }

            if (open > at) AddText(builder, markup.Substring(at, open - at), ref sequence, pad);

            var close = markup.IndexOf('>', open);

            if (close < 0)
            {
                // An unterminated tag is text, not a broken element: a
                // template being typed into is unparseable most of the time.
                AddText(builder, markup.Substring(open), ref sequence, pad);
                break;
            }

            var tag = markup.Substring(open + 1, close - open - 1).Trim();

            if (tag.StartsWith("/", StringComparison.Ordinal))
            {
                builder.AppendLine($"{pad}__builder.CloseElement()");
            }
            else
            {
                var selfClosing = tag.EndsWith("/", StringComparison.Ordinal);
                var name = Name(tag);
                var attributes = tag.Substring(name.Length).TrimEnd('/').Trim();

                builder.AppendLine($"{pad}__builder.OpenElement({sequence++}, \"{name}\")");

                WriteAttributes(builder, attributes, ref sequence, pad);

                if (selfClosing || IsVoid(name))
                    builder.AppendLine($"{pad}__builder.CloseElement()");
            }

            at = close + 1;
        }
    }

    private static void AddText(
        StringBuilder builder, string text, ref int sequence, string pad)
    {
        if (text.Length == 0) return;

        // AddMarkupContent, not AddContent: literal markup from the template
        // is already markup, and AddContent encodes it — the line breaks
        // between elements came out as &#xA; in the page.
        builder.AppendLine($"{pad}__builder.AddMarkupContent({sequence++}, {Quoted(text)})");
    }

    private static void WriteAttributes(
        StringBuilder builder, string attributes, ref int sequence, string pad)
    {
        foreach (var (name, value) in Attributes(attributes))
        {
            // An @ in the value is Visual Basic, not text: onclick="@Handler"
            // has to reach AddAttribute as an expression or the handler is
            // registered as the literal string.
            var written = value.StartsWith("@", StringComparison.Ordinal)
                ? value.Substring(1)
                : Quoted(value);

            builder.AppendLine($"{pad}__builder.AddAttribute({sequence++}, \"{name}\", {written})");
        }
    }

    /// <summary>The attributes in a tag, as name and value.</summary>
    private static IEnumerable<(string Name, string Value)> Attributes(string text)
    {
        var at = 0;

        while (at < text.Length)
        {
            while (at < text.Length && char.IsWhiteSpace(text[at])) at++;

            if (at >= text.Length) break;

            var equals = text.IndexOf('=', at);

            if (equals < 0)
            {
                // A bare attribute is true, the way "disabled" is in HTML.
                var bare = text.Substring(at).Trim();

                if (bare.Length > 0) yield return (bare, "@True");

                break;
            }

            var name = text.Substring(at, equals - at).Trim();
            var from = equals + 1;

            while (from < text.Length && char.IsWhiteSpace(text[from])) from++;

            if (from >= text.Length) break;

            var quote = text[from];

            if (quote is '"' or '\'')
            {
                var end = text.IndexOf(quote, from + 1);

                if (end < 0) break;

                yield return (name, text.Substring(from + 1, end - from - 1));
                at = end + 1;
            }
            else
            {
                var end = from;

                while (end < text.Length && !char.IsWhiteSpace(text[end])) end++;

                yield return (name, text.Substring(from, end - from));
                at = end;
            }
        }
    }

    /// <summary>The element name at the start of a tag.</summary>
    private static string Name(string tag)
    {
        var end = 0;

        while (end < tag.Length && !char.IsWhiteSpace(tag[end]) && tag[end] != '/') end++;

        return tag.Substring(0, end);
    }

    /// <summary>
    /// Whether an element closes itself in HTML.
    /// </summary>
    /// <remarks>
    /// A void element has no closing tag to find, so without this the builder
    /// is left with an element open and everything after it nests inside a
    /// &lt;br&gt; — the tree stays unbalanced to the end of the component.
    /// </remarks>
    private static bool IsVoid(string name) => name.ToLowerInvariant() is
        "area" or "base" or "br" or "col" or "embed" or "hr" or "img" or
        "input" or "link" or "meta" or "source" or "track" or "wbr";

    /// <summary>
    /// A Visual Basic string literal.
    /// </summary>
    /// <remarks>
    /// Line breaks become vbLf rather than being written into the literal:
    /// Visual Basic has no multi-line string, so markup spanning lines — which
    /// is all markup — produced a literal broken across lines and a file that
    /// did not compile.
    /// </remarks>
    private static string Quoted(string text)
    {
        var parts = text.Replace("\r\n", "\n").Split('\n');
        var pieces = new List<string>();

        for (var i = 0; i < parts.Length; i++)
        {
            if (i > 0) pieces.Add("Global.Microsoft.VisualBasic.Constants.vbLf");

            if (parts[i].Length > 0)
                pieces.Add("\"" + parts[i].Replace("\"", "\"\"") + "\"");
        }

        return pieces.Count == 0 ? "\"\"" : string.Join(" & ", pieces);
    }
}
