using System.Text;

namespace Basalt.Razor.Vb;

/// <summary>
/// Turns a parsed template into a Visual Basic class.
///
/// The generated class writes the page into a StringBuilder: literal markup is
/// appended verbatim, expressions are HTML-encoded unless the template asked
/// for raw output, and control flow becomes the Visual Basic statements it was
/// written as.
/// </summary>
public static class VbHtmlCodeWriter
{
    /// <summary>Base class the generated views inherit from.</summary>
    public const string BaseTypeName = "Basalt.Razor.Vb.Runtime.VbHtmlView";

    /// <summary>Base class for views served by ASP.NET Core.</summary>
    public const string AspNetCoreBaseTypeName = "Microsoft.AspNetCore.Mvc.Razor.RazorPage";

    /// <summary>Base class for a Razor Page, which is not the same one.</summary>
    public const string RazorPageBaseTypeName = "Microsoft.AspNetCore.Mvc.RazorPages.Page";

    /// <summary>Whether a host is served by ASP.NET Core, either kind.</summary>
    private static bool IsWeb(ViewHost host) => host != ViewHost.Standalone;

    /// <summary>
    /// The generated Visual Basic, and the table tying it to the template.
    ///
    /// The two come out together because they are written together: a mapping
    /// entry and its #ExternalSource are produced by the same scope, so they
    /// cannot drift apart. Razor's compiler is built the same way, for the
    /// same reason.
    /// </summary>
    public sealed record Generated(string Code, SourceMap Map)
    {
        public override string ToString() => Code;
    }

    /// <summary>
    /// Writes the class, with no mapping table.
    ///
    /// Kept because most callers only want the code; the mapping matters to
    /// the tooling, not to the compiler.
    /// </summary>
    public static string Write(
        VbHtmlDocument document, string className, string namespaceName,
        ViewHost host = ViewHost.Standalone) =>
        WriteWithMap(document, className, namespaceName, filePath: null, host).Code;

    /// <summary>
    /// Writes the class along with its mapping table.
    ///
    /// <paramref name="filePath"/> is what goes in the #ExternalSource
    /// directives; without one they are left out, since a pragma naming no
    /// file would send the compiler nowhere.
    /// </summary>
    public static Generated WriteWithMap(
        VbHtmlDocument document, string className, string namespaceName, string? filePath,
        ViewHost host = ViewHost.Standalone)
    {
        var builder = new StringBuilder();
        var mappings = new List<SourceMapping>();

        builder.AppendLine("' <auto-generated>");
        builder.AppendLine("'     Generated from a .vbhtml template. Changes will be lost.");
        builder.AppendLine("' </auto-generated>");
        builder.AppendLine();
        builder.AppendLine("Option Strict Off");
        builder.AppendLine("Option Explicit On");
        builder.AppendLine();
        builder.AppendLine("Imports System");
        builder.AppendLine("Imports System.Text");

        if (IsWeb(host))
        {
            // The one-argument Html.PartialAsync and most of the tag helpers
            // are extension methods; without their namespaces in scope the
            // compiler reports a missing argument, which points at the call
            // rather than at the missing import.
            builder.AppendLine("Imports Microsoft.AspNetCore.Mvc");
            builder.AppendLine("Imports Microsoft.AspNetCore.Mvc.Rendering");
            builder.AppendLine("Imports Microsoft.AspNetCore.Mvc.ViewFeatures");
            builder.AppendLine("Imports Microsoft.AspNetCore.Html");
            // WriteAttribute for pages served by ASP.NET Core, which the base
            // class does not provide: it is an extension in the integration
            // package.
            builder.AppendLine("Imports Basalt.Razor.Vb.AspNetCore");
        }

        foreach (var import in document.Imports)
            builder.AppendLine($"Imports {import}");

        builder.AppendLine();
        // A template may name its own namespace, which is what a project
        // with an unusual folder layout needs.
        if (!string.IsNullOrWhiteSpace(document.Namespace))
            namespaceName = document.Namespace!;

        builder.AppendLine($"Namespace {namespaceName}");
        builder.AppendLine();
        foreach (var attribute in document.Attributes)
            builder.AppendLine($"    <{attribute.Trim('<', '>')}>");

        // How the framework maps a compiled page back to its path, as the
        // C# generator writes it. Without it a page is compiled, registered,
        // and never routed to: a 404 with nothing in the log.
        if (host == ViewHost.RazorPage && document.PageIdentifier is { Length: > 0 } identifier)
        {
            builder.AppendLine(
                "    <Global.Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemMetadata(" +
                $"\"Identifier\", {Quote(identifier)})>");
        }

        // Escaped: Error.vbhtml is in every scaffolded MVC project and Error
        // is a keyword, so the generated class would not compile.
        builder.AppendLine($"    Partial Public Class {ViewNaming.Escape(className)}");
        // A template may name its own base class; without one it gets the
        // runtime's.
        // A template may use @Model without declaring @ModelType, as Razor
        // allows; without a declared type it is late-bound, which Option
        // Strict Off permits.
        var modelTypeName = string.IsNullOrWhiteSpace(document.ModelType)
            ? "Object"
            : Qualify(document.ModelType!);

        var baseType = string.IsNullOrWhiteSpace(document.Inherits)
            ? host switch
            {
                // A Razor Page inherits RazorPages.Page, which is not the
                // same class as MVC's RazorPage and is not generic: the page
                // carries its model on its own PageModel.
                ViewHost.RazorPage => RazorPageBaseTypeName,

                // Generic in the model even when untyped: MVC hands the view
                // its model through this base, and the non-generic RazorPage
                // has no Model to hand it to.
                ViewHost.AspNetCore => $"{AspNetCoreBaseTypeName}(Of {modelTypeName})",

                _ => BaseTypeName,
            }
            : document.Inherits!;

        builder.AppendLine($"        Inherits {baseType}");

        foreach (var contract in document.Implements)
            builder.AppendLine($"        Implements {contract}");
        builder.AppendLine();

        // Under ASP.NET Core the base class already carries Model, typed by
        // the generic argument; declaring it again would shadow the one the
        // framework populates and every view would see Nothing.
        if (host == ViewHost.Standalone)
        {
            builder.AppendLine($"        Public Property Model As {modelTypeName}");
            builder.AppendLine();
        }
        else if (host == ViewHost.RazorPage)
        {
            // A Razor Page must expose Model and ViewData typed on its page
            // model; the framework rejects a page without them, by name, at
            // startup. Without a declared @ModelType the page has no model of
            // its own and PageModel stands in, which is what a page with only
            // markup gets in C# too.
            // PageModel itself is abstract, so a page with no @ModelType
            // cannot use it directly: the container fails to construct one at
            // request time, not at startup. A concrete model is generated for
            // it below, which is what the .vbhtml.vb file would hold if the
            // author had written one.
            var pageModelType = string.IsNullOrWhiteSpace(document.ModelType)
                ? $"{ViewNaming.Escape(className)}GeneratedModel"
                : modelTypeName;

            // Both read from PageContext rather than from a base-class
            // member, which is where the C# generator takes them from too.
            builder.AppendLine(
                $"        Public ReadOnly Property ViewData As Global.Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary(Of {pageModelType})");
            builder.AppendLine("            Get");
            builder.AppendLine(
                $"                Return CType(PageContext.ViewData, Global.Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary(Of {pageModelType}))");
            builder.AppendLine("            End Get");
            builder.AppendLine("        End Property");
            builder.AppendLine();

            builder.AppendLine($"        Public ReadOnly Property Model As {pageModelType}");
            builder.AppendLine("            Get");
            builder.AppendLine("                Return ViewData.Model");
            builder.AppendLine("            End Get");
            builder.AppendLine("        End Property");
            builder.AppendLine();

            builder.AppendLine(
                "        <Global.Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInject>");
            builder.AppendLine(
                $"        Public Property Html As Global.Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper(Of {pageModelType})");
            builder.AppendLine(
                "        <Global.Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInject>");
            builder.AppendLine(
                "        Public Property Url As Global.Microsoft.AspNetCore.Mvc.IUrlHelper");

            foreach (var service in document.Injected)
            {
                builder.AppendLine(
                    "        <Global.Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInject>");
                builder.AppendLine(
                    $"        Public Property {service.Name} As {Qualify(service.Type)}");
            }

            builder.AppendLine();
        }
        else
        {
            // @Html and @Url are what a Razor view is written against, and
            // the base class does not carry them: MVC fills in properties
            // marked with RazorInject, which is how the C# views get theirs.
            builder.AppendLine(
                "        <Global.Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInject>");
            builder.AppendLine(
                $"        Public Property Html As Global.Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper(Of {modelTypeName})");
            builder.AppendLine(
                "        <Global.Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInject>");
            builder.AppendLine(
                "        Public Property Url As Global.Microsoft.AspNetCore.Mvc.IUrlHelper");
            builder.AppendLine(
                "        <Global.Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInject>");
            builder.AppendLine(
                "        Public Property Component As Global.Microsoft.AspNetCore.Mvc.IViewComponentHelper");

            // What @Inject asked for, filled in by the container exactly as
            // Html and Url are.
            foreach (var service in document.Injected)
            {
                builder.AppendLine(
                    "        <Global.Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInject>");
                builder.AppendLine(
                    $"        Public Property {service.Name} As {Qualify(service.Type)}");
            }

            builder.AppendLine();
        }

        builder.AppendLine(IsWeb(host)
            ? "        Public Overrides Async Function ExecuteAsync() As System.Threading.Tasks.Task"
            : "        Public Overrides Sub Execute()");

        // A layout the folder's _ViewStart set. Written first so a Layout the
        // template assigns itself overwrites it, which is the order Razor
        // resolves them in.
        if (!string.IsNullOrWhiteSpace(document.DefaultLayout))
            builder.AppendLine($"            Layout = {Quote(document.DefaultLayout!)}");

        WriteNodes(builder, document.Nodes, indent: 3, mappings, filePath, host);

        if (IsWeb(host))
        {
            // A view with no awaits would warn that the method runs
            // synchronously; the signature is fixed by the base class, so the
            // await is supplied rather than the signature changed.
            builder.AppendLine("            Await System.Threading.Tasks.Task.CompletedTask");
            builder.AppendLine("        End Function");
        }
        else
        {
            builder.AppendLine("        End Sub");
        }

        builder.AppendLine();

        // Members the template declared for itself, written into the class
        // rather than into Execute: a method cannot live inside a method.
        foreach (var members in document.Functions)
        {
            foreach (var line in SplitLines(members))
                builder.AppendLine($"        {line}");

            builder.AppendLine();
        }

        builder.AppendLine("    End Class");
        builder.AppendLine();

        // The concrete page model for a page that declared none. PageModel is
        // abstract, and the container reports that only when the first
        // request arrives — long after the page looked fine.
        if (host == ViewHost.RazorPage && string.IsNullOrWhiteSpace(document.ModelType))
        {
            builder.AppendLine(
                $"    Public Class {ViewNaming.Escape(className)}GeneratedModel");
            builder.AppendLine(
                "        Inherits Global.Microsoft.AspNetCore.Mvc.RazorPages.PageModel");
            builder.AppendLine("    End Class");
            builder.AppendLine();
        }

        builder.AppendLine("End Namespace");

        return new Generated(builder.ToString(), new SourceMap(mappings));
    }

    /// <summary>
    /// Writes something that came from the template, wrapped in a pragma and
    /// recorded in the mapping table.
    ///
    /// The two are produced here together and nowhere else, so a mapping
    /// without its pragma — or the other way round — cannot happen. That is
    /// the whole reason this method exists rather than two calls at each site.
    ///
    /// #ExternalSource maps by line, not by column: Visual Basic has no
    /// column-accurate form of it, unlike the C# #line the Razor compiler
    /// uses. An error therefore lands on the right line of the template but
    /// not necessarily under the right character.
    /// </summary>
    /// <summary>How many lines a run of the builder holds.</summary>
    private static int LinesIn(StringBuilder builder, int start, int length)
    {
        var lines = 1;
        var end = start + length;

        for (var at = start; at < end && at < builder.Length; at++)
            if (builder[at] == '\n' && at + 1 < end) lines++;

        return lines;
    }

    private static void WriteMapped(
        StringBuilder builder,
        List<SourceMapping> mappings,
        string? filePath,
        int originalPosition,
        int originalLength,
        int originalLine,
        Action write)
    {
        if (filePath is null)
        {
            write();
            return;
        }

        builder.AppendLine($"#ExternalSource({PragmaPath(filePath)}, {originalLine})");

        var generatedStart = builder.Length;
        var generatedLine = CountLines(builder, generatedStart);

        write();

        var generatedLength = builder.Length - generatedStart;

        builder.AppendLine("#End ExternalSource");

        mappings.Add(new SourceMapping(
            new SourceSpan(originalPosition, originalLength),
            new SourceSpan(generatedStart, generatedLength),
            originalLine,
            generatedLine));

        // A multi-line region needs one entry per line. Its lines are written
        // out in the same order they were read, so the second template line
        // is the second generated line, and so on. Without this a caret
        // anywhere below the first line of a Code block mapped to nothing at
        // all, and every delegated feature went quiet there.
        var writtenLines = LinesIn(builder, generatedStart, generatedLength);

        for (var offset = 1; offset < writtenLines; offset++)
        {
            mappings.Add(new SourceMapping(
                new SourceSpan(originalPosition, originalLength),
                new SourceSpan(generatedStart, generatedLength),
                originalLine + offset,
                generatedLine + offset));
        }
    }

    /// <summary>
    /// A file path as a pragma can carry it.
    ///
    /// A quote in the name would end the string early, and a stray one turns
    /// the rest of the generated file into nonsense. Razor hit the same class
    /// of problem with Windows separators and had to fix it; this doubles the
    /// quotes rather than trusting the name.
    /// </summary>
    private static string PragmaPath(string path) =>
        "\"" + path.Replace("\"", "\"\"") + "\"";

    /// <summary>How many lines have been written so far, counted from one.</summary>
    private static int CountLines(StringBuilder builder, int upTo)
    {
        var lines = 1;

        for (var i = 0; i < upTo; i++)
            if (builder[i] == '\n') lines++;

        return lines;
    }

    private static void WriteNodes(
        StringBuilder builder, List<VbHtmlNode> nodes, int indent,
        List<SourceMapping> mappings, string? filePath, ViewHost host)
    {
        for (var i = 0; i < nodes.Count; i++)
        {
            // An attribute whose whole value is one expression is written as
            // a unit, so that Nothing or False can remove it. Three nodes:
            // the literal ending in name=", the expression, the literal
            // starting with ".
            if (TryWriteConditionalAttribute(builder, nodes, i, indent, mappings, filePath, host))
            {
                // Two, not three: the closing literal opens the next
                // attribute as well, and consuming it here made a second
                // conditional attribute on the same tag go unrecognised —
                // rendering disabled="False", which disables the control.
                // Its leading quote is dropped, the rest written by the
                // ordinary path below.
                i += 1;

                if (nodes[i + 1] is HtmlNode tail && tail.Text.Length > 1)
                    nodes[i + 1] = new HtmlNode(
                        tail.Text.Substring(1), tail.Position + 1, tail.Line);
                else
                    i += 1;

                continue;
            }

            WriteNode(builder, nodes[i], indent, mappings, filePath, host);
        }
    }

    /// <summary>
    /// Writes an attribute whose value is a single expression, when the three
    /// nodes at this position are one.
    ///
    /// Razor drops an attribute whose value is Nothing or False —
    /// <c>disabled="@isDisabled"</c> must not render as
    /// <c>disabled="False"</c>, which every browser reads as disabled. The
    /// exception is data-*, which is data rather than behaviour and keeps
    /// whatever it is given.
    /// </summary>
    /// <summary>
    /// Writes a run of markup, rewriting any tag helpers in it.
    /// </summary>
    /// <remarks>
    /// The single place markup is emitted. It was two, and the second — the
    /// literal in front of a conditional attribute — bypassed the rewriting:
    /// asp-action reached the browser untouched whenever the same run also
    /// held an attribute like disabled="@locked".
    ///
    /// Rewritten here rather than before parsing: moving text around first
    /// would shift every offset after it, and the #ExternalSource lines would
    /// point at the wrong place — a fault that hides rather than announces
    /// itself.
    /// </remarks>
    private static void WriteMarkup(
        StringBuilder builder, string markup, string pad, ViewHost host)
    {
        if (markup.Length == 0) return;

        if (!IsWeb(host))
        {
            builder.AppendLine($"{pad}WriteLiteral({Quote(markup)})");
            return;
        }

        foreach (var piece in TagHelperRewriting.Rewrite(markup))
        {
            builder.AppendLine(piece.IsExpression
                ? $"{pad}Write({piece.Text})"
                : $"{pad}WriteLiteral({Quote(piece.Text)})");
        }
    }

    private static bool TryWriteConditionalAttribute(
        StringBuilder builder, List<VbHtmlNode> nodes, int index, int indent,
        List<SourceMapping> mappings, string? filePath, ViewHost host)
    {
        if (index + 2 >= nodes.Count) return false;

        if (nodes[index] is not HtmlNode before ||
            nodes[index + 1] is not ExpressionNode value ||
            nodes[index + 2] is not HtmlNode after)
            return false;

        // Raw is an explicit instruction about encoding; leave it alone.
        if (value.IsRaw || value.Expression.Length == 0) return false;

        if (AttributeNameAt(before.Text) is not { } name) return false;

        // The value must end where the expression ends: anything else and
        // this is one part of a composed value, not the whole of it.
        if (after.Text.Length == 0 || after.Text[0] != '"') return false;

        // data-* carries data, not behaviour: False is a value there.
        if (name.StartsWith("data-", StringComparison.OrdinalIgnoreCase)) return false;

        var pad = new string(' ', indent * 4);

        // The literal up to the attribute name, minus the space in front of
        // it: WriteAttribute writes its own, so that removing the attribute
        // removes the space with it rather than leaving "<input  />".
        var prefix = before.Text
            .Substring(0, before.Text.Length - AttributeSuffixLength(name))
            .TrimEnd(' ', '\t');

        if (prefix.Length > 0)
            WriteMarkup(builder, prefix, pad, host);

        WriteMapped(builder, mappings, filePath, value.Position,
            value.Expression.Length, value.Line, () =>
                builder.AppendLine($"{pad}WriteAttribute({Quote(name)}, {value.Expression})"));

        return true;
    }

    /// <summary>
    /// The attribute name a literal ends on, when it ends with <c>name="</c>.
    ///
    /// Null when the literal ends any other way, which is every case that is
    /// not a whole attribute value.
    /// </summary>
    private static string? AttributeNameAt(string text)
    {
        if (text.Length < 3 || text[text.Length - 1] != '"') return null;
        if (text[text.Length - 2] != '=') return null;

        var end = text.Length - 2;
        var start = end;

        while (start > 0 && IsAttributeNameCharacter(text[start - 1])) start--;

        if (start == end) return null;

        // A name must follow whitespace inside a tag, not run on from
        // something else.
        if (start > 0 && !char.IsWhiteSpace(text[start - 1])) return null;

        return text.Substring(start, end - start);
    }

    private static int AttributeSuffixLength(string name) => name.Length + 2;

    private static bool IsAttributeNameCharacter(char c) =>
        char.IsLetterOrDigit(c) || c == '-' || c == '_' || c == ':';

    private static void WriteNode(
        StringBuilder builder, VbHtmlNode node, int indent,
        List<SourceMapping> mappings, string? filePath, ViewHost host)
    {
        var pad = new string(' ', indent * 4);

        switch (node)
        {
            case HtmlNode html:
                // Nothing to emit for whitespace-only runs between statements.
                if (html.Text.Length == 0) return;

                WriteMarkup(builder, html.Text, pad, host);
                return;

            case ExpressionNode expression:
                if (expression.Expression.Length == 0) return;

                // Mapped: an error in the expression belongs on the template
                // line the user wrote it on.
                // An awaited call is written as its own statement: Write of
                // an awaited value would put the Task's type name on the page,
                // and the helpers that matter here all return one.
                var written = expression.IsAwaited
                    ? $"Await {expression.Expression}"
                    : expression.Expression;

                WriteMapped(builder, mappings, filePath, expression.Position,
                    expression.Expression.Length, expression.Line, () =>
                        builder.AppendLine(expression.IsRaw
                            ? $"{pad}WriteRaw({written})"
                            : $"{pad}Write({written})"));
                return;

            case StatementNode statement:
                // From where the body starts, not from the keyword: the
                // length is the body's, so anchoring at "@Code" made the
                // entry cover the keyword and stop short of the body's own
                // end — and a caret past that point mapped nowhere, which is
                // why hover inside a Code block answered nothing.
                WriteMapped(builder, mappings, filePath, statement.BodyPosition,
                    statement.Code.Length, statement.BodyLine, () =>
                    {
                        foreach (var line in SplitLines(statement.Code))
                            builder.AppendLine($"{pad}{line}");
                    });
                return;

            case DirectiveNode:
                // Directives shape the class, not its body.
                return;

            case FunctionsNode:
                // Written into the class, not here.
                return;

            case SectionNode section:
                // The body is deferred: a section declared at the top of a
                // view often belongs at the bottom of the page, and only the
                // layout knows where.
                // ASP.NET Core's DefineSection takes a RenderAsyncDelegate,
                // which a plain Sub does not satisfy; the standalone runtime
                // takes the Sub. Same directive, two shapes.
                if (IsWeb(host))
                {
                    builder.AppendLine(
                        $"{pad}DefineSection({Quote(section.Name)}, Async Function() As System.Threading.Tasks.Task");
                    WriteNodes(builder, section.Body, indent + 1, mappings, filePath, host);
                    builder.AppendLine($"{pad}    Await System.Threading.Tasks.Task.CompletedTask");
                    builder.AppendLine($"{pad}End Function)");
                    return;
                }

                builder.AppendLine($"{pad}DefineSection({Quote(section.Name)}, Sub()");
                WriteNodes(builder, section.Body, indent + 1, mappings, filePath, host);
                builder.AppendLine($"{pad}End Sub)");
                return;

            case BlockNode block:
                // Mapped like any other code, which it had never been: the
                // opening clause is where the interesting expression of a
                // block lives — "@If ViewData("x").ToString().Length > 4" is
                // three calls deep — and without an entry the caret reached
                // nothing, so completion and hover answered nothing inside
                // it. Errors in the condition landed on the wrong line too.
                WriteMapped(builder, mappings, filePath, block.Position + 1,
                    block.Opening.Length, block.Line, () =>
                        builder.AppendLine($"{pad}{block.Opening}"));

                WriteNodes(builder, block.Body, indent + 1, mappings, filePath, host);

                foreach (var clause in block.Clauses)
                {
                    builder.AppendLine($"{pad}{clause.Keyword}");
                    WriteNodes(builder, clause.Body, indent + 1, mappings, filePath, host);
                }

                builder.AppendLine($"{pad}{block.Closing}");
                return;
        }
    }

    private static IEnumerable<string> SplitLines(string code) =>
        code.Split('\n').Select(l => l.TrimEnd('\r')).Where(l => l.Trim().Length > 0);

    /// <summary>
    /// Renders text as a Visual Basic string literal.
    ///
    /// Visual Basic has no escape sequences inside literals: a quote is doubled,
    /// and a newline has to be concatenated from Environment.NewLine. Splitting
    /// on newlines keeps the generated source readable and the literals valid.
    /// </summary>
    /// <summary>
    /// Roots a model type at the global namespace.
    /// </summary>
    /// <remarks>
    /// A view generated into Acme.Web.Views.Home resolves "Acme.Web.Models.X"
    /// relative to its own namespace first and fails to find it. Razor
    /// qualifies C# model types for the same reason; the template author
    /// should not have to write Global. to be understood.
    /// </remarks>
    private static string Qualify(string modelType)
    {
        var trimmed = modelType.Trim();

        // Already rooted, a generic, an array, or a keyword like Object:
        // leave every one of these alone rather than guess at their shape.
        if (trimmed.Length == 0) return trimmed;
        if (trimmed.StartsWith("Global.", StringComparison.OrdinalIgnoreCase)) return trimmed;
        if (!trimmed.Contains(".")) return trimmed;
        if (trimmed.IndexOfAny(['(', '[', ' ']) >= 0) return trimmed;

        return "Global." + trimmed;
    }

    private static string Quote(string text)
    {
        var lines = text.Split('\n');
        var parts = new List<string>();

        for (var i = 0; i < lines.Length; i++)
        {
            var line = lines[i].TrimEnd('\r');

            if (line.Length > 0)
                parts.Add("\"" + line.Replace("\"", "\"\"") + "\"");

            // Every split point except the last stood for a newline.
            if (i < lines.Length - 1) parts.Add("vbCrLf");
        }

        return parts.Count == 0 ? "\"\"" : string.Join(" & ", parts);
    }
}
