using System.Text;

namespace Basalt.Vb6;

/// <summary>
/// Writes a Visual Basic 6 form as a class that runs.
/// </summary>
/// <remarks>
/// Where the three halves meet: the controls come from the .frm's designer
/// block, the handlers from its code, and both are written against the
/// Basalt.Vb6.Runtime controls that sit on Avalonia.
///
/// One class, not the two Visual Studio splits a form into. A .frm is one file
/// and stays one file: splitting it would mean writing the designer half back
/// out somewhere, and the whole approach rests on never rewriting what Visual
/// Basic 6 wrote.
/// </remarks>
public static class FormToVisualBasic
{
    /// <summary>What writing a form produced.</summary>
    public sealed record Result(
        string Code,
        IReadOnlyList<CodeTranslation.Note> Notes,
        IReadOnlyList<string> Missing);

    /// <summary>The runtime control each intrinsic VB6 control becomes.</summary>
    private static readonly Dictionary<string, string> Equivalents =
        new(StringComparer.OrdinalIgnoreCase)
        {
            ["VB.TextBox"] = "Vb6TextBox",
            ["VB.CommandButton"] = "Vb6CommandButton",
            ["VB.Label"] = "Vb6Label",
            ["VB.CheckBox"] = "Vb6CheckBox",
            ["VB.OptionButton"] = "Vb6OptionButton",
            ["VB.ListBox"] = "Vb6ListBox",
            ["VB.Frame"] = "Vb6Frame",
        };

    /// <summary>Writes the class for a form.</summary>
    public static Result Write(FormFile form, string className, string? filePath = null)
    {
        var controls = Flatten(form.Root.Children).ToList();

        var supported = controls
            .Where(c => Equivalents.ContainsKey(c.Type))
            .ToList();

        var missing = controls
            .Where(c => !Equivalents.ContainsKey(c.Type))
            .Select(c => $"{c.Name} ({c.Type})")
            .ToList();

        // Only the controls that exist can be handled: a Handles clause naming
        // a control the class does not declare stops the file compiling, so a
        // handler for a missing OCX has to stay an ordinary method.
        var translated = CodeTranslation.Translate(
            form.Code, supported.Select(c => c.Name).ToList());

        var builder = new StringBuilder();

        builder.AppendLine("' <auto-generated>");
        builder.AppendLine("'     Written by Basalt from a Visual Basic 6 form.");
        builder.AppendLine("'     The .frm it came from is unchanged and still opens in VB6.");
        builder.AppendLine("' </auto-generated>");
        builder.AppendLine("Option Strict Off");
        builder.AppendLine("Option Explicit On");
        builder.AppendLine();
        builder.AppendLine("Imports Basalt.Vb6.Runtime");

        // Before Microsoft.VisualBasic, so MsgBox and InputBox resolve to the
        // ones that work here: the originals are still in the framework and
        // throw "Method requires System.Windows.Forms" on anything but
        // Windows, so a converted form compiles and dies at the first message
        // it shows — which is the first thing anyone does with it.
        builder.AppendLine("Imports Basalt.Vb6.Runtime.Vb6Dialogs");
        builder.AppendLine("Imports Microsoft.VisualBasic");
        builder.AppendLine();
        builder.AppendLine($"Public Class {className}");
        builder.AppendLine("    Inherits Global.Basalt.Vb6.Runtime.Vb6Form");
        builder.AppendLine();

        // WithEvents on every one, because a handler is wired by a Handles
        // clause and a field without WithEvents cannot carry one.
        foreach (var control in supported)
            builder.AppendLine(
                $"    Private WithEvents {control.Name} As New " +
                $"Global.Basalt.Vb6.Runtime.{Equivalents[control.Type]}()");

        if (missing.Count > 0)
        {
            builder.AppendLine();
            builder.AppendLine("    ' Controls from an OCX this machine does not have. They are");
            builder.AppendLine("    ' named here so the gap is visible in the code as well as on");
            builder.AppendLine("    ' the form:");

            foreach (var name in missing)
                builder.AppendLine($"    '     {name}");
        }

        builder.AppendLine();
        builder.AppendLine("    Public Sub New()");
        builder.AppendLine($"        Caption = {Quote(form.Root.Text("Caption") ?? className)}");

        if (form.Root.Properties.ContainsKey("ClientWidth"))
            builder.AppendLine($"        ScaleWidth = {form.Root.Number("ClientWidth")}");

        if (form.Root.Properties.ContainsKey("ClientHeight"))
            builder.AppendLine($"        ScaleHeight = {form.Root.Number("ClientHeight")}");

        builder.AppendLine();

        foreach (var control in supported)
            WriteControl(builder, control, form.Root, supported);

        builder.AppendLine("    End Sub");

        if (translated.Code.Trim().Length > 0)
        {
            builder.AppendLine();

            // With the file the code came from, so an error is reported
            // against the .frm and a breakpoint set there is hit. Measured:
            // the runtime believes it is inside Form1.frm and names it in a
            // stack trace.
            if (filePath is not null)
                builder.AppendLine($"#ExternalSource(\"{filePath.Replace("\\", "\\\\")}\", {form.CodeLine})");

            foreach (var line in translated.Code.Replace("\r\n", "\n").Split('\n'))
                builder.AppendLine(line.Length == 0 ? "" : "    " + line);

            if (filePath is not null)
                builder.AppendLine("#End ExternalSource");
        }

        builder.AppendLine("End Class");

        return new Result(builder.ToString(), translated.Notes, missing);
    }

    private static void WriteControl(
        StringBuilder builder,
        FormControl control,
        FormControl root,
        IReadOnlyList<FormControl> supported)
    {
        var name = control.Name;

        builder.AppendLine($"        {name}.Name = {Quote(name)}");

        foreach (var property in new[] { "Left", "Top", "Width", "Height" })
            if (control.Properties.ContainsKey(property))
                builder.AppendLine($"        {name}.{property} = {control.Number(property)}");

        // Caption on a button or a label, Text in a box: the .frm uses whichever
        // the control has, and so does the class.
        if (control.Text("Caption") is { } caption)
            builder.AppendLine($"        {name}.Caption = {Quote(caption)}");

        if (control.Text("Text") is { } text)
            builder.AppendLine($"        {name}.Text = {Quote(text)}");

        if (control.Text("Enabled") is "0" or "False")
            builder.AppendLine($"        {name}.Enabled = False");

        if (control.Text("Visible") is "0" or "False")
            builder.AppendLine($"        {name}.Visible = False");

        // Into whatever holds it. A control inside a frame goes on the frame,
        // not on the form: putting it on the form leaves a group's contents
        // loose, which is visible immediately and wrong quietly.
        var parent = ParentOf(control, root);

        var into = parent is not null
                && !ReferenceEquals(parent, root)
                && supported.Any(c => ReferenceEquals(c, parent))
            ? parent.Name
            : null;

        builder.AppendLine(into is null
            ? $"        Add({name})"
            : $"        {into}.Add({name})");

        builder.AppendLine();
    }

    /// <summary>Which control holds this one.</summary>
    private static FormControl? ParentOf(FormControl control, FormControl within)
    {
        foreach (var child in within.Children)
        {
            if (ReferenceEquals(child, control)) return within;

            if (ParentOf(control, child) is { } found) return found;
        }

        return null;
    }

    private static IEnumerable<FormControl> Flatten(IEnumerable<FormControl> controls)
    {
        foreach (var control in controls)
        {
            yield return control;

            foreach (var child in Flatten(control.Children)) yield return child;
        }
    }

    private static string Quote(string text) =>
        "\"" + text.Replace("\"", "\"\"") + "\"";
}
