package com.basalt.vbrazor

import com.intellij.lang.Language
import com.intellij.openapi.fileTypes.LanguageFileType
import javax.swing.Icon

/**
 * The language a .vbhtml file is written in.
 *
 * Registered without a parser: the language server understands the format, and
 * a second parser in Kotlin would be a chance for the two to disagree.
 */
object VbHtmlLanguage : Language("vbhtml", "text/vbhtml") {
    private fun readResolve(): Any = VbHtmlLanguage

    override fun getDisplayName(): String = "Razor (Visual Basic)"
}

/**
 * The .vbhtml file type, so the IDE opens these files as this language.
 *
 * No INSTANCE field of its own: a Kotlin object already has one, generated by
 * the compiler, and declaring a second with the same name is a clash the build
 * refuses. The platform finds the object through the implementationClass in
 * plugin.xml, so nothing needs to name it in code.
 */
object VbHtmlFileType : LanguageFileType(VbHtmlLanguage) {

    override fun getName(): String = "Razor (Visual Basic)"

    override fun getDescription(): String = "Razor view written in Visual Basic"

    override fun getDefaultExtension(): String = "vbhtml"

    override fun getIcon(): Icon? = null
}

/**
 * The language a .vbp page is written in.
 *
 * Separate from the view's language because the delimiters differ — &lt;% %&gt;
 * rather than @ — and the platform keys a grammar and a file type to a
 * language, not to an extension.
 */
object VbPageLanguage : Language("vbp", "text/vbp") {
    private fun readResolve(): Any = VbPageLanguage

    override fun getDisplayName(): String = "Basalt Page (Visual Basic)"
}

/** The .vbp file type. */
object VbPageFileType : LanguageFileType(VbPageLanguage) {

    override fun getName(): String = "Basalt Page (Visual Basic)"

    override fun getDescription(): String = "Page written in Visual Basic, in the Classic ASP shape"

    override fun getDefaultExtension(): String = "vbp"

    override fun getIcon(): Icon? = null
}
