using System.Text;

namespace Basalt.Razor.Vb.Classic;

/// <summary>
/// Turns a parsed <c>.vbpage</c> page into a Visual Basic class.
/// </summary>
/// <remarks>
/// The class is a request handler with one method: it writes the page and
/// returns. No model, no controller, no registration — the file is the unit,
/// which is what makes this feel like PHP rather than like MVC.
///
/// What it does not carry over from Classic ASP: values are HTML-encoded
/// unless the page asks otherwise, Option Strict is left on, and there are no
/// ambient globals — Request and Response are properties of the page, so what
/// a page touches can be read off its own source.
/// </remarks>
public static class VbPageWriter
{
    /// <summary>Base class the generated pages inherit from.</summary>
    public const string BaseTypeName = "Basalt.Web.VbPage";

    /// <summary>Writes the class for a page.</summary>
    public static string Write(
        VbPageParser.Page page, string className, string namespaceName, string? filePath = null) =>
        WriteWithMap(page, className, namespaceName, filePath).Code;

    public sealed record Generated(string Code, SourceMap Map);

    /// <summary>Writes the runtime's page class and the exact source spans used by editor features.</summary>
    public static Generated WriteWithMap(
        VbPageParser.Page page, string className, string namespaceName, string? filePath = null)
    {
        var builder = new StringBuilder();
        var mappings = new List<SourceMapping>();

        builder.AppendLine("' <auto-generated>");
        builder.AppendLine("'     Generated from a .vbpage page. Changes will be lost.");
        builder.AppendLine("' </auto-generated>");
        builder.AppendLine();

        // Strict on, unlike Classic ASP: a page that adds a number to a string
        // and gets away with it is a page that fails on the one input nobody
        // tried. Explicit too, so a typo is an error rather than a new
        // variable holding Nothing.
        builder.AppendLine("Option Strict On");
        builder.AppendLine("Option Explicit On");
        builder.AppendLine();
        builder.AppendLine("Imports System");
        builder.AppendLine("Imports System.Threading.Tasks");
        builder.AppendLine("Imports Basalt.Web");

        for (var index = 0; index < page.Imports.Count; index++)
        {
            var import = page.Imports[index];
            if (index < page.ImportDirectives.Count)
            {
                var source = page.ImportDirectives[index];
                WriteFragment(builder, mappings, filePath, import, source.Position, source.Line, "Imports ", "", "", preserveNewlines: true);
            }
            else builder.AppendLine($"Imports {import}");
        }

        builder.AppendLine();
        builder.AppendLine($"Namespace {namespaceName}");
        builder.AppendLine();
        builder.AppendLine($"    Public Class {ViewNaming.Escape(className)}");
        builder.AppendLine($"        Inherits Global.{BaseTypeName}");
        builder.AppendLine();
        builder.AppendLine("        Public Overrides Async Function RenderAsync() As Task");

        foreach (var part in page.Parts) WritePart(builder, mappings, part, filePath);

        builder.AppendLine("            Await Task.CompletedTask");
        builder.AppendLine("        End Function");

        for (var index = 0; index < page.Members.Count; index++)
        {
            builder.AppendLine();
            var members = page.Members[index];
            if (index < page.MemberBlocks.Count)
            {
                var source = page.MemberBlocks[index];
                WriteFragment(builder, mappings, filePath, members, source.Position, source.BodyLine, "        ", "", "        ");
            }
            else
                foreach (var line in members.Split('\n'))
                    builder.AppendLine($"        {line.TrimEnd('\r')}");
        }

        builder.AppendLine();
        builder.AppendLine("    End Class");
        builder.AppendLine();
        builder.AppendLine("End Namespace");

        return new Generated(builder.ToString(), new SourceMap(mappings));
    }

    private static void WritePart(
        StringBuilder builder, List<SourceMapping> mappings, VbPageParser.PagePart part, string? filePath)
    {
        const string pad = "            ";

        switch (part)
        {
            case VbPageParser.Markup markup:
                if (markup.Text.Length == 0) return;

                builder.AppendLine($"{pad}WriteLiteral({Quote(markup.Text)})");
                return;

            case VbPageParser.Expression expression:
                WriteFragment(builder, mappings, filePath, expression.Text,
                    expression.Position, expression.BodyLine,
                    expression.Raw ? pad + "WriteRaw(" : pad + "Write(", ")", "", preserveNewlines: true);
                return;

            case VbPageParser.Code code:
                WriteFragment(builder, mappings, filePath, code.Text,
                    code.Position, code.BodyLine, pad, "", pad);
                return;
        }
    }

    /// <summary>
    /// Wraps emitted code in the pragma that points errors back at the page.
    /// </summary>
    /// <remarks>
    /// Without it an error in a page is reported against generated code the
    /// author never wrote, at a line number that means nothing to them.
    /// </remarks>
    private static void WriteFragment(
        StringBuilder builder, List<SourceMapping> mappings, string? filePath,
        string text, int originalPosition, int originalLine,
        string prefix, string suffix, string continuationPrefix, bool preserveNewlines = false)
    {
        // Keep the shared pragma writer's line-for-line emission. Exact line
        // spans replace its whole-block mappings here so inverse offsets do
        // not count the indentation added before every generated line.
        ExternalSourceWriter.WriteMapped(builder, new List<SourceMapping>(), filePath,
            originalPosition, text.Length, originalLine, () =>
            {
                var lines = text.Split('\n');
                var originalAt = originalPosition;
                for (var index = 0; index < lines.Length; index++)
                {
                    var line = lines[index].TrimEnd('\r');
                    builder.Append(index == 0 ? prefix : continuationPrefix);
                    var generatedAt = builder.Length;
                    var generatedLine = ExternalSourceWriter.CountLines(builder, generatedAt);
                    var indent = 0;
                    while (indent < line.Length && (line[indent] == ' ' || line[indent] == '\t')) indent++;
                    builder.Append(line);
                    if (index == lines.Length - 1) builder.Append(suffix);
                    if (preserveNewlines && index < lines.Length - 1)
                        builder.Append(lines[index].EndsWith("\r", StringComparison.Ordinal) ? "\r\n" : "\n");
                    else builder.AppendLine();
                    if (filePath is not null)
                        mappings.Add(new SourceMapping(
                            new SourceSpan(originalAt + indent, line.Length - indent),
                            new SourceSpan(generatedAt + indent, line.Length - indent),
                            originalLine + index, generatedLine));
                    originalAt += lines[index].Length + 1;
                }
            });
    }

    /// <summary>A Visual Basic string literal, with line breaks written out.</summary>
    private static string Quote(string text)
    {
        var builder = new StringBuilder("\"");

        foreach (var c in text)
        {
            switch (c)
            {
                case '"': builder.Append("\"\""); break;
                case '\r': break;
                case '\n': builder.Append("\" & vbCrLf & \""); break;
                default: builder.Append(c); break;
            }
        }

        return builder.Append('"').ToString();
    }
}
