using System.Text;

namespace Basalt.Razor.Vb.Classic;

/// <summary>
/// Turns a parsed <c>.vbpage</c> page into a Visual Basic class.
/// </summary>
/// <remarks>
/// The class is a request handler with one method: it writes the page and
/// returns. No model, no controller, no registration — the file is the unit,
/// which is what makes this feel like PHP rather than like MVC.
///
/// What it does not carry over from Classic ASP: values are HTML-encoded
/// unless the page asks otherwise, Option Strict is left on, and there are no
/// ambient globals — Request and Response are properties of the page, so what
/// a page touches can be read off its own source.
/// </remarks>
public static class VbPageWriter
{
    /// <summary>Base class the generated pages inherit from.</summary>
    public const string BaseTypeName = "Basalt.Web.VbPage";

    /// <summary>Writes the class for a page.</summary>
    public static string Write(
        VbPageParser.Page page, string className, string namespaceName, string? filePath = null)
    {
        var builder = new StringBuilder();

        builder.AppendLine("' <auto-generated>");
        builder.AppendLine("'     Generated from a .vbpage page. Changes will be lost.");
        builder.AppendLine("' </auto-generated>");
        builder.AppendLine();

        // Strict on, unlike Classic ASP: a page that adds a number to a string
        // and gets away with it is a page that fails on the one input nobody
        // tried. Explicit too, so a typo is an error rather than a new
        // variable holding Nothing.
        builder.AppendLine("Option Strict On");
        builder.AppendLine("Option Explicit On");
        builder.AppendLine();
        builder.AppendLine("Imports System");
        builder.AppendLine("Imports System.Threading.Tasks");
        builder.AppendLine("Imports Basalt.Web");

        foreach (var import in page.Imports)
            builder.AppendLine($"Imports {import}");

        builder.AppendLine();
        builder.AppendLine($"Namespace {namespaceName}");
        builder.AppendLine();
        builder.AppendLine($"    Public Class {ViewNaming.Escape(className)}");
        builder.AppendLine($"        Inherits Global.{BaseTypeName}");
        builder.AppendLine();
        builder.AppendLine("        Public Overrides Async Function RenderAsync() As Task");

        foreach (var part in page.Parts) WritePart(builder, part, filePath);

        builder.AppendLine("            Await Task.CompletedTask");
        builder.AppendLine("        End Function");

        foreach (var members in page.Members)
        {
            builder.AppendLine();

            foreach (var line in members.Split('\n'))
                builder.AppendLine($"        {line.TrimEnd('\r')}");
        }

        builder.AppendLine();
        builder.AppendLine("    End Class");
        builder.AppendLine();
        builder.AppendLine("End Namespace");

        return builder.ToString();
    }

    private static void WritePart(StringBuilder builder, VbPageParser.PagePart part, string? filePath)
    {
        const string pad = "            ";

        switch (part)
        {
            case VbPageParser.Markup markup:
                if (markup.Text.Length == 0) return;

                builder.AppendLine($"{pad}WriteLiteral({Quote(markup.Text)})");
                return;

            case VbPageParser.Expression expression:
                WithPragma(builder, filePath, expression.Line, () =>
                    builder.AppendLine(expression.Raw
                        ? $"{pad}WriteRaw({expression.Text})"
                        : $"{pad}Write({expression.Text})"));
                return;

            case VbPageParser.Code code:
                WithPragma(builder, filePath, code.Line, () =>
                {
                    foreach (var line in code.Text.Split('\n'))
                        builder.AppendLine($"{pad}{line.TrimEnd('\r')}");
                });
                return;
        }
    }

    /// <summary>
    /// Wraps emitted code in the pragma that points errors back at the page.
    /// </summary>
    /// <remarks>
    /// Without it an error in a page is reported against generated code the
    /// author never wrote, at a line number that means nothing to them.
    /// </remarks>
    private static void WithPragma(
        StringBuilder builder, string? filePath, int line, Action write)
    {
        var mapped = filePath is { Length: > 0 };

        if (mapped) builder.AppendLine($"#ExternalSource(\"{filePath!.Replace("\"", "\"\"")}\", {line})");

        write();

        if (mapped) builder.AppendLine("#End ExternalSource");
    }

    /// <summary>A Visual Basic string literal, with line breaks written out.</summary>
    private static string Quote(string text)
    {
        var builder = new StringBuilder("\"");

        foreach (var c in text)
        {
            switch (c)
            {
                case '"': builder.Append("\"\""); break;
                case '\r': break;
                case '\n': builder.Append("\" & vbCrLf & \""); break;
                default: builder.Append(c); break;
            }
        }

        return builder.Append('"').ToString();
    }
}
